### ISSUE TITLE
 DB table ip field does not initialize value

### ISSUE THREAD

**Issue by bluepoet** [janbols/spock-dbunit#4] opened 2017-01-12 07:02 UTC
@janbols 

Hi!

I initialized the value in the ip field of the DB table as below, but it does not contain the value.

```
 @DbUnit(configure = { IDatabaseTester it ->
        it.setUpOperation = DatabaseOperation.CLEAN_INSERT
    })
def content = {
    User(name: 'test1', ip: '1.2.3.4')
    User(name: 'test2', ip: '127.0.0.1')
}
```

What should I do?

Please confirm.

Your help is very much appreciated!

**Comment by janbols** [comment] 2017-01-12 20:28
Hi, I don't know how your table looks like, what columns it has. Perhaps there's a PK somewhere that you didn't define. The way it's set up here it looks like you have a table called User with 2 columns called 'name' and 'ip'. If not, then that's probably the cause. I added a test containing your example that should pass on https://github.com/janbols/spock-dbunit/blob/master/src/test/groovy/be/janbols/spock/extension.dbunit/Issue4Test.groovy

Hope this helps.
Jan

**Comment by bluepoet** [comment] 2017-01-13 02:02
@janbols 

Thank you for your response.

I have tried to execute the insert statement by changing the insert statement like below.

```
Def content = {
    User (name: 'test1', ip: '1.2.3.4')
    User (name: 'test2')
}
```

If you insert the row data with the ip first, then the row data without the ip, the ip field will contain the value.
Probably the first thing you have to guess is that the insert sql statement that was executed was executed.

Please review below.

https://github.com/janbols/spock-dbunit/pull/5

**Comment by janbols** [comment] 2017-01-13 21:41
Ok @bluepoet , I understand your problem now. The first row (in our case, the first User item) defines the columns dbUnit will use. So if you put `User (name: 'test2')` first, it will assume there's only 1 column. This is a flaw of dbUnit and I don't know if we can easily do something about this, though I agree it is rather annoying and I also bumped into the same issue before.
See http://dbunit.sourceforge.net/faq.html#differentcolumnnumber

**Comment by janbols** [comment] 2017-03-26 19:32
Closing this issue because it's not something we can do something about.

**Closed as completed by janbols** 2017-03-26 19:32 UTC
